# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170226_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
